// Auto-generated by export_vexflow.py — do not edit by hand.
// Re-run `python export_vexflow.py` (or add_song.py) to refresh.
window.SONGS = [
  {
    "id": "442661_8",
    "song_id": 442661,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Dance Macabre",
    "lyrics": false
  },
  {
    "id": "441770_9",
    "song_id": 441770,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Rats",
    "lyrics": true
  },
  {
    "id": "412647_8",
    "song_id": 412647,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Square Hammer",
    "lyrics": true
  },
  {
    "id": "19_8",
    "song_id": 19,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "Enter Sandman",
    "lyrics": true
  },
  {
    "id": "14_6",
    "song_id": 14,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "Come As You Are",
    "lyrics": true
  },
  {
    "id": "31_6",
    "song_id": 31,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "Heart-Shaped Box",
    "lyrics": true
  },
  {
    "id": "295_5",
    "song_id": 295,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "In Bloom",
    "lyrics": true
  },
  {
    "id": "269_5",
    "song_id": 269,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "Smells Like Teen Spirit",
    "lyrics": true
  },
  {
    "id": "7346_5",
    "song_id": 7346,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "The Man Who Sold The World",
    "lyrics": true
  },
  {
    "id": "16093_3",
    "song_id": 16093,
    "part_id": 3,
    "instrument": "drums",
    "artist": "Pixies",
    "title": "Wave Of Mutilation",
    "lyrics": false
  },
  {
    "id": "97_6",
    "song_id": 97,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Radiohead",
    "title": "Creep",
    "lyrics": true
  },
  {
    "id": "89089_8",
    "song_id": 89089,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Survivor",
    "title": "Eye Of The Tiger",
    "lyrics": true
  },
  {
    "id": "431_5",
    "song_id": 431,
    "part_id": 5,
    "instrument": "drums",
    "artist": "The Cranberries",
    "title": "Zombie",
    "lyrics": true
  }
];
