// Auto-generated by export_vexflow.py — do not edit by hand.
// Re-run `python export_vexflow.py` (or add_song.py) to refresh.
window.SONGS = [
  {
    "id": "1024_6",
    "song_id": 1024,
    "part_id": 6,
    "instrument": "drums",
    "artist": "AC/DC",
    "title": "Back In Black",
    "name": "Drums | Phil Rudd | Sonor Phonic Series",
    "lyrics": true
  },
  {
    "id": "289_6",
    "song_id": 289,
    "part_id": 6,
    "instrument": "drums",
    "artist": "AC/DC",
    "title": "Highway To Hell",
    "name": "Phil Rudd | Gretsch \"Phonics\" Custom Kit | Drums",
    "lyrics": true
  },
  {
    "id": "1352_6",
    "song_id": 1352,
    "part_id": 6,
    "instrument": "drums",
    "artist": "AC/DC",
    "title": "Thunderstruck",
    "name": "Chris Slade | Pearl Reference Series | Drums",
    "lyrics": true
  },
  {
    "id": "258_11",
    "song_id": 258,
    "part_id": 11,
    "instrument": "drums",
    "artist": "blink-182",
    "title": "All The Small Things",
    "name": "Travis Barker | Orange County Kit | Drums",
    "lyrics": true
  },
  {
    "id": "27109_7",
    "song_id": 27109,
    "part_id": 7,
    "instrument": "drums",
    "artist": "blink-182",
    "title": "Dammit",
    "name": "Scott Raynor | Pork Pie Maple Custom Kit | Drums",
    "lyrics": true
  },
  {
    "id": "6703_7",
    "song_id": 6703,
    "part_id": 7,
    "instrument": "drums",
    "artist": "blink-182",
    "title": "First Date",
    "name": "Travis Barker | Orange County Kit | Drums",
    "lyrics": true
  },
  {
    "id": "1386_8",
    "song_id": 1386,
    "part_id": 8,
    "instrument": "drums",
    "artist": "blink-182",
    "title": "I Miss You",
    "name": "Travis Barker | Orange County Kit | Drums",
    "lyrics": true
  },
  {
    "id": "741_7",
    "song_id": 741,
    "part_id": 7,
    "instrument": "drums",
    "artist": "blink-182",
    "title": "What's My Age Again?",
    "name": "Travis Barker | Orange County Kit | Drums",
    "lyrics": true
  },
  {
    "id": "3131_7",
    "song_id": 3131,
    "part_id": 7,
    "instrument": "drums",
    "artist": "Bon Jovi",
    "title": "Livin' On A Prayer",
    "name": "Tico Torres | Drums",
    "lyrics": true
  },
  {
    "id": "329_5",
    "song_id": 329,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Deep Purple",
    "title": "Smoke On The Water",
    "name": "Ian Paice | Ludwig Classic Maple | Drums",
    "lyrics": true
  },
  {
    "id": "334_13",
    "song_id": 334,
    "part_id": 13,
    "instrument": "drums",
    "artist": "Dragonforce",
    "title": "Through The Fire And Flames",
    "name": "Dave Mackintosh | Tama Starclassic Custom Kit | Drums",
    "lyrics": true
  },
  {
    "id": "9000002_3",
    "song_id": 9000002,
    "part_id": 3,
    "instrument": "drums",
    "artist": "Duke Ellington",
    "title": "Satin Doll",
    "name": "Drums | Full chart w/ intro + tag | Medium Swing ♩=106",
    "lyrics": false
  },
  {
    "id": "86505_7",
    "song_id": 86505,
    "part_id": 7,
    "instrument": "drums",
    "artist": "Foo Fighters",
    "title": "Everlong",
    "name": "Dave Grohl | Tama Artstar II | Drums",
    "lyrics": true
  },
  {
    "id": "500775_9",
    "song_id": 500775,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Call Me Little Sunshine",
    "name": "Mountain",
    "lyrics": false
  },
  {
    "id": "442661_8",
    "song_id": 442661,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Dance Macabre",
    "name": "Drums - Mountain",
    "lyrics": false
  },
  {
    "id": "4831516_3",
    "song_id": 4831516,
    "part_id": 3,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Hunter's Moon",
    "name": "",
    "lyrics": false
  },
  {
    "id": "441770_9",
    "song_id": 441770,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Rats",
    "name": "Mountain",
    "lyrics": true
  },
  {
    "id": "412647_2",
    "song_id": 412647,
    "part_id": 2,
    "instrument": "guitar",
    "artist": "Ghost",
    "title": "Square Hammer",
    "name": "Fire - Lead",
    "lyrics": true
  },
  {
    "id": "412647_3",
    "song_id": 412647,
    "part_id": 3,
    "instrument": "guitar",
    "artist": "Ghost",
    "title": "Square Hammer",
    "name": "Aether - Rhythm",
    "lyrics": true
  },
  {
    "id": "412647_4",
    "song_id": 412647,
    "part_id": 4,
    "instrument": "bass",
    "artist": "Ghost",
    "title": "Square Hammer",
    "name": "Water",
    "lyrics": true
  },
  {
    "id": "412647_8",
    "song_id": 412647,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Ghost",
    "title": "Square Hammer",
    "name": "Earth",
    "lyrics": true
  },
  {
    "id": "1401_4",
    "song_id": 1401,
    "part_id": 4,
    "instrument": "drums",
    "artist": "Green Day",
    "title": "Basket Case",
    "name": "Tré Cool | DW Collector's Series Custom Kit | Drumset",
    "lyrics": true
  },
  {
    "id": "23_8",
    "song_id": 23,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Guns N' Roses",
    "title": "Sweet Child O' Mine",
    "name": "Steven Adler | Gretsch Drums",
    "lyrics": true
  },
  {
    "id": "9000001_1",
    "song_id": 9000001,
    "part_id": 1,
    "instrument": "drums",
    "artist": "Horace Silver",
    "title": "Song For My Father",
    "name": "Drums | Simple skeleton (teacher) | Latin",
    "lyrics": true
  },
  {
    "id": "9000001_2",
    "song_id": 9000001,
    "part_id": 2,
    "instrument": "drums",
    "artist": "Horace Silver",
    "title": "Song For My Father",
    "name": "Drums | Skeleton + fills (bars 8/16/24) | Latin",
    "lyrics": true
  },
  {
    "id": "11053_9",
    "song_id": 11053,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Kansas",
    "title": "Carry On Wayward Son",
    "name": "Phil Ehart - Drums",
    "lyrics": true
  },
  {
    "id": "487_6",
    "song_id": 487,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Megadeth",
    "title": "Symphony Of Destruction",
    "name": "Nick Menza | Tama Artstar Custom Drums",
    "lyrics": true
  },
  {
    "id": "19_8",
    "song_id": 19,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "Enter Sandman",
    "name": "Lars Ulrich | TAMA Artstar II | Drums",
    "lyrics": true
  },
  {
    "id": "572_8",
    "song_id": 572,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "For Whom The Bell Tolls",
    "name": "Lars Ulrich | TAMA Imperialstar | Drums",
    "lyrics": true
  },
  {
    "id": "455118_9",
    "song_id": 455118,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "Master of Puppets",
    "name": "Lars Ulrich | Tama Superstar Birch Kit | Drums",
    "lyrics": true
  },
  {
    "id": "439171_13",
    "song_id": 439171,
    "part_id": 13,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "Nothing Else Matters",
    "name": "Lars Ulrich | TAMA Artstar II | Drums",
    "lyrics": true
  },
  {
    "id": "444_12",
    "song_id": 444,
    "part_id": 12,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "One",
    "name": "Lars Ulrich | Tama Starclassic Kit | Drums",
    "lyrics": true
  },
  {
    "id": "317_11",
    "song_id": 317,
    "part_id": 11,
    "instrument": "drums",
    "artist": "Metallica",
    "title": "Sad But True",
    "name": "Lars Ulrich | TAMA Starclassic Maple | Drums",
    "lyrics": true
  },
  {
    "id": "12719_9",
    "song_id": 12719,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Mötley Crüe",
    "title": "Kickstart My Heart",
    "name": "Tommy Lee | DW Collectors Series Custom | Drums",
    "lyrics": true
  },
  {
    "id": "14_6",
    "song_id": 14,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "Come As You Are",
    "name": "Dave Grohl | Tama Granstar | Drums",
    "lyrics": true
  },
  {
    "id": "31_6",
    "song_id": 31,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "Heart-Shaped Box",
    "name": "Dave Grohl | Tama Granstar Kit | Drums",
    "lyrics": true
  },
  {
    "id": "295_5",
    "song_id": 295,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "In Bloom",
    "name": "Dave Grohl | Tama Artstar II | Drums",
    "lyrics": true
  },
  {
    "id": "269_5",
    "song_id": 269,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "Smells Like Teen Spirit",
    "name": "Dave Grohl | Tama Granstar | Drums",
    "lyrics": true
  },
  {
    "id": "7346_5",
    "song_id": 7346,
    "part_id": 5,
    "instrument": "drums",
    "artist": "Nirvana",
    "title": "The Man Who Sold The World",
    "name": "Dave Grohl - Drums | Vintage Slingerland Drum Kit",
    "lyrics": true
  },
  {
    "id": "2_11",
    "song_id": 2,
    "part_id": 11,
    "instrument": "drums",
    "artist": "Oasis",
    "title": "Wonderwall",
    "name": "Alan \"Whitey\" White | Ludwig Super Classic | Drums",
    "lyrics": true
  },
  {
    "id": "50420_9",
    "song_id": 50420,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Phil Collins",
    "title": "In The Air Tonight",
    "name": "Phil Collins - Premier Concert Kit | Drums",
    "lyrics": true
  },
  {
    "id": "16093_3",
    "song_id": 16093,
    "part_id": 3,
    "instrument": "drums",
    "artist": "Pixies",
    "title": "Wave Of Mutilation",
    "name": "David Lovering",
    "lyrics": false
  },
  {
    "id": "371_6",
    "song_id": 371,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Queen",
    "title": "Another One Bites the Dust",
    "name": "Roger Taylor | Drum Loops",
    "lyrics": true
  },
  {
    "id": "97_6",
    "song_id": 97,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Radiohead",
    "title": "Creep",
    "name": "Philip Selway | DW Collector's Series | Drums",
    "lyrics": true
  },
  {
    "id": "360_7",
    "song_id": 360,
    "part_id": 7,
    "instrument": "drums",
    "artist": "Rage Against The Machine",
    "title": "Killing in the Name",
    "name": "Brad Wilk | Grestch Kit | Drums",
    "lyrics": true
  },
  {
    "id": "12_6",
    "song_id": 12,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Red Hot Chili Peppers",
    "title": "Can't Stop",
    "name": "Chad Smith | Pearl Masters Custom Silver Sparkle | Drums",
    "lyrics": true
  },
  {
    "id": "287_6",
    "song_id": 287,
    "part_id": 6,
    "instrument": "drums",
    "artist": "Rush",
    "title": "Tom Sawyer",
    "name": "Neil Peart | Tama \"Old Faithful\" Custom Kit | Drums",
    "lyrics": true
  },
  {
    "id": "1379_9",
    "song_id": 1379,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Slipknot",
    "title": "Before I Forget",
    "name": "Joey Jordison | Orange County Custom Kit | Drums",
    "lyrics": true
  },
  {
    "id": "18211_9",
    "song_id": 18211,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Slipknot",
    "title": "Duality",
    "name": "Joey Jordison | Orange County Custom Kit | Drums",
    "lyrics": true
  },
  {
    "id": "19615_12",
    "song_id": 19615,
    "part_id": 12,
    "instrument": "drums",
    "artist": "Slipknot",
    "title": "Psychosocial",
    "name": "Joey Jordison | Drums | Pearl Masters Kit |",
    "lyrics": true
  },
  {
    "id": "89089_8",
    "song_id": 89089,
    "part_id": 8,
    "instrument": "drums",
    "artist": "Survivor",
    "title": "Eye Of The Tiger",
    "name": "Marc Droubay | Ludwig Drums",
    "lyrics": true
  },
  {
    "id": "431_5",
    "song_id": 431,
    "part_id": 5,
    "instrument": "drums",
    "artist": "The Cranberries",
    "title": "Zombie",
    "name": "Fergal Lawler | DW Collector Series Kit | Drums",
    "lyrics": true
  },
  {
    "id": "3706_7",
    "song_id": 3706,
    "part_id": 7,
    "instrument": "drums",
    "artist": "The Police",
    "title": "Message In A Bottle",
    "name": "Stewart Copeland | Tama Imperialstar",
    "lyrics": true
  },
  {
    "id": "51025_15",
    "song_id": 51025,
    "part_id": 15,
    "instrument": "drums",
    "artist": "Toto",
    "title": "Africa",
    "name": "Jeff Porcaro | Drums",
    "lyrics": true
  },
  {
    "id": "19993_18",
    "song_id": 19993,
    "part_id": 18,
    "instrument": "drums",
    "artist": "Toto",
    "title": "Rosanna",
    "name": "Jeff Porcaro",
    "lyrics": false
  },
  {
    "id": "20359_9",
    "song_id": 20359,
    "part_id": 9,
    "instrument": "drums",
    "artist": "Type O Negative",
    "title": "Black No. 1 (Little Miss Scare-All)",
    "name": "Sal Abruscato | Drums",
    "lyrics": true
  },
  {
    "id": "29601_10",
    "song_id": 29601,
    "part_id": 10,
    "instrument": "drums",
    "artist": "Type O Negative",
    "title": "Love You To Death",
    "name": "Johnny Kelly",
    "lyrics": true
  },
  {
    "id": "19632_3",
    "song_id": 19632,
    "part_id": 3,
    "instrument": "drums",
    "artist": "Van Halen",
    "title": "Hot For Teacher",
    "name": "Alex Van Halen | Lead kit - Ludwig Classic Maple",
    "lyrics": true
  }
];
